schoolproject/credentials/urls.py
from . import views
from django.urls import path

urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),



]

schoolproject/persons/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path('add/', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),  # AJAX
    path('order_confirm', views.order_confirm, name='order_confirm'),
    # path('home/', include("schoolapp.urls")),
    # path('home/logout/', include("credentials.urls")),
]

schoolproject/schoolapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('form', views.form, name='form'),
]

schoolproject/schoolproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from schoolproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
    path('credentials/',include('credentials.urls')),
    path('persons/',include('persons.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

schoolproject/credentials/models.py
from django.db import models

# Create your models here.

schoolproject/persons/models.py
from django import forms
from django.core.exceptions import ValidationError
from django.db import models
from django.forms import EmailInput


# Create your models here.


class Department(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name




class Person(models.Model):

    name = models.CharField(max_length=124)
    dob = models.DateTimeField(auto_now=False,auto_now_add=False)
    age = models.IntegerField()
    phone_number = models.CharField(max_length=10)
    e_mail = models.EmailField()
    address = models.TextField(blank=True)
    gender=models.CharField(max_length=100)
    materials_provided=models.CharField(max_length=100)
    purpose = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self):
        return self.name

schoolproject/persons/forms.py
from django import forms

from .models import Person, Course


class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).all(

                )
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')


GENDER_CHOICES= [('Male','Male'),('Female','Female'),('Other','Other')]
MATERIALS_PROVIDED = [('Pen','Pen'), ('Debit Notebook','Debit Notebook'), ('Exam Papers','Exam Papers')]
PURPOSE= [('Enquiry','Enquiry'),('Place Order','Place Order'),('Return','Return')]

class PersonCreationForm(forms.ModelForm):
    dob=forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES, widget=forms.RadioSelect)
    materials_provided = forms.MultipleChoiceField(
        choices=MATERIALS_PROVIDED, widget=forms.CheckboxSelectMultiple)
    purpose=forms.CharField(
        widget=forms.Select(choices=PURPOSE))
    class Meta:
        model = Person
        fields = '__all__'

schoolproject/credentials/views.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import auth,messages


# Create your views here.
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('home')
        else:
            messages.info(request,'INVALID CREDENTIALS')
            return redirect('login')

    return render(request,"login.html")




def register(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['password1']

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username Taken")
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                messages.success(request, "User Created")
                return redirect('login')

        else:
            messages.info(request,"Password Not Matching")
            return redirect('register')
        return redirect('/')


    return render(request,"register.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

schoolproject/persons/views.py
from django.contrib import auth
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PersonCreationForm
from .models import Person, Course


def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('order_confirm')
    return render(request, 'form.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'order_confirm.html', {'form': form})


# AJAX
def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'dropdown.html', {'courses': courses})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)
def order_confirm(request):
    if request.method == 'POST':
        return redirect('/')
    return render(request,'order_confirm.html')

schoolproject/schoolapp/views.py
from django.contrib.auth import login

from django.shortcuts import render




# Create your views here.
def index(request):
    return render(request,"index.html")

def home(request):
    return render(request,"home.html")

def form(request):
    return render(request,"form.html")

schoolproject/templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Educenter</title>
  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">
  <!-- animation css -->
  <link rel="stylesheet" href="{% static 'plugins/animate/animate.css' %}">
  <!-- aos -->
  <link rel="stylesheet" href="{% static 'plugins/aos/aos.css' %}">
  <!-- venobox popup -->
  <link rel="stylesheet" href="{% static 'plugins/venobox/venobox.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

</head>
<body>
<header class="fixed-top header">
 <div class="navigation w-100">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light p-0">
        <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
          aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav ml-auto text-center">
            <li class="nav-item @@home">
              <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item dropdown view">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Department
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Biology">Biology Science</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics">Mathematics</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/English_language">English language</a>
                <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">Humanities</a>
              </div>
            </li>
            {% if user.is_authenticated %}
            <li class="list-inline-item" style="padding:20px;"><button type="submit" class="btn btn-primary">Hello {{user.username}}</button> </li>
            <li class="list-inline-item" style="padding:20px;"><a href="{% url 'logout' %}"><button type="submit" class="btn btn-primary">LOGOUT</button></a></li>

									{% else %}
             <li class="list-inline-item" style="padding:20px;"><a href="{% url 'login' %}"><button type="submit" class="btn btn-primary">LOGIN</button></a></li>
            <li class="list-inline-item" style="padding:20px;"><a href="{% url 'register' %}"><button type="submit" class="btn btn-primary">REGISTER</button></a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>
<section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <ul class="list-inline custom-breadcrumb">
          <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="@@page-link">EduCenter</a></li>
          <li class="list-inline-item text-white h3 font-secondary @@nasted"></li>
        </ul>
        <p class="text-lighten">Our courses offer a good compromise between the continuous assessment favoured by some universities and the emphasis placed on final exams by others.</p>
      </div>
    </div>
  </div>
</section>
{% block content %}
{% endblock %}
<footer class="bg-light text-center text-lg-start fixed-bottom">
  <!-- copyright -->
  <div class="copyright py-4 bg-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 text-sm-left text-center">
          <p class="mb-0">Copyright
            <script>
              var CurrentYear = new Date().getFullYear()
              document.write(CurrentYear)
            </script>
            © <a href="https://themefisher.com">Educenter</a></p> . All Rights Reserved.
        </div>
        <div class="col-sm-5 text-sm-right text-center">
          <ul class="list-inline">
            <li class="list-inline-item"><a class="d-inline-block p-2" href="https://www.facebook.com/themefisher"><i class="ti-facebook text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="https://www.twitter.com/themefisher"><i class="ti-twitter-alt text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="#"><i class="ti-instagram text-primary"></i></a></li>
            <li class="list-inline-item"><a class="d-inline-block p-2" href="https://dribbble.com/themefisher"><i class="ti-dribbble text-primary"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<!-- venobox popup -->
<script src="{% static 'plugins/venobox/venobox.min.js' %}"></script>
<!-- mixitup filter -->
<script src="{% static 'plugins/mixitup/mixitup.min.js' %}"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
<script src="{% static 'plugins/google-map/gmap.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>
 </body>

</html>

schoolproject/templates/dropdown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}
</body>
</html>

schoolproject/templates/form.html
	<h2>Form</h2>

<form method="post" id="personForm" data-courses-url="{% url 'ajax_load_courses' %}">

    {% csrf_token %}

    {{ form.as_p }}

<!--    <a href="order_confirm"><input type="submit" value="Submit"></a>-->
    <button type="submit" class="btn btn-primary">SUBMIT</button>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#personForm").attr("data-courses-url");  // get the url of the `load_courses` view
        const departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-courses/ )
            data: {
                'department_id': departmentId       // add the department id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
                $("#id_course").html(data);  // replace the contents of the course input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);

                */
            }
        });

    });
</script>

schoolproject/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="zxx">


<body>
{% block content %}

<center><li  style="padding-top:30px;" class="list-inline-item"><a href="{% url 'person_add' %}"><button type="submit" class="btn btn-primary">Submit Form</button></a></li></center>


{% endblock %}
</body>
</html>

schoolproject/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="zxx">

<body>
{% block content %}

<!-- courses -->
<section class="section-sm">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="d-flex align-items-center section-title justify-content-between">
          <h2 class="mb-0 text-nowrap mr-3">Our Courses</h2>

      </div>
    </div>
    <!-- course list -->
<div class="row justify-content-center">
  <!-- course item -->
  <div class="col-lg-4 col-sm-6 mb-5">
    <div class="card p-0 border-primary rounded-0 hover-shadow">
      <img class="card-img-top rounded-0" src="{% static 'images/courses/course2.jpg' %}" alt="course thumb">
      <div class="card-body">
        <ul class="list-inline mb-2">
          <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
          <li class="list-inline-item"><a class="text-color" href="#">Biology Science</a></li>
        </ul>
        <a href="course-single.html">
          <h4 class="card-title">Botony</h4>
        </a>
        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna.</p>
        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
      </div>
    </div>
  </div>
  <!-- course item -->
  <div class="col-lg-4 col-sm-6 mb-5">
    <div class="card p-0 border-primary rounded-0 hover-shadow">
      <img class="card-img-top rounded-0" src="{% static 'images/courses/course3.jpg' %}" alt="course thumb">
      <div class="card-body">
        <ul class="list-inline mb-2">
          <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
          <li class="list-inline-item"><a class="text-color" href="#">Biology Science</a></li>
        </ul>
        <a href="course-single.html">
          <h4 class="card-title">Zoology</h4>
        </a>
        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna.</p>
        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
      </div>
    </div>
  </div>
  <!-- course item -->
  <div class="col-lg-4 col-sm-6 mb-5">
    <div class="card p-0 border-primary rounded-0 hover-shadow">
      <img class="card-img-top rounded-0" src="{% static 'images/courses/course4.jpg' %}" alt="course thumb">
      <div class="card-body">
        <ul class="list-inline mb-2">
          <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
          <li class="list-inline-item"><a class="text-color" href="#">Computer Science</a></li>
        </ul>
        <a href="course-single.html">
          <h4 class="card-title">Python Programming</h4>
        </a>
        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna.</p>
        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
      </div>
    </div>
  </div>
  <!-- course item -->
  <div class="col-lg-4 col-sm-6 mb-5">
    <div class="card p-0 border-primary rounded-0 hover-shadow">
      <img class="card-img-top rounded-0" src="{% static 'images/courses/course4.jpg' %}" alt="course thumb">
      <div class="card-body">
        <ul class="list-inline mb-2">
          <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
          <li class="list-inline-item"><a class="text-color" href="#">Computer Science</a></li>
        </ul>
        <a href="course-single.html">
          <h4 class="card-title">C Programming</h4>
        </a>
        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna.</p>
        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
      </div>
    </div>
  </div>
  <!-- course item -->
  <div class="col-lg-4 col-sm-6 mb-5">
    <div class="card p-0 border-primary rounded-0 hover-shadow">
      <img class="card-img-top rounded-0" src="{% static 'images/courses/course2.jpg' %}" alt="course thumb">
      <div class="card-body">
        <ul class="list-inline mb-2">
          <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
          <li class="list-inline-item"><a class="text-color" href="#">Commerce</a></li>
        </ul>
        <a href="course-single.html">
          <h4 class="card-title">B.Com</h4>
        </a>
        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna.</p>
        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
      </div>
    </div>
  </div>
  <!-- course item -->
  <div class="col-lg-4 col-sm-6 mb-5">
    <div class="card p-0 border-primary rounded-0 hover-shadow">
      <img class="card-img-top rounded-0" src="{% static 'images/courses/course3.jpg' %}" alt="course thumb">
      <div class="card-body">
        <ul class="list-inline mb-2">
          <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
          <li class="list-inline-item"><a class="text-color" href="#">Commerce</a></li>
        </ul>
        <a href="course-single.html">
          <h4 class="card-title">M.Com</h4>
        </a>
        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna.</p>
        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
      </div>
    </div>
  </div>
</div>
    {% endblock %}
</body>
</html>

schoolproject/templates/login.html
<!DOCTYPE html>

{% load static %}
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Educenter</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">
  <!-- animation css -->
  <link rel="stylesheet" href="{% static 'plugins/animate/animate.css' %}">
  <!-- aos -->
  <link rel="stylesheet" href="{% static 'plugins/aos/aos.css' %}">
  <!-- venobox popup -->
  <link rel="stylesheet" href="{% static 'plugins/venobox/venobox.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

</head>

<body>




<!-- Modal -->
<div  id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content rounded-0 border-0 p-4">
            <div class="modal-header border-0">
                 <h3>LOGIN</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                </button>
            </div>
            <div class="modal-body">
                <form class="signup-form" action="login" method="post" class="row">
                    {% csrf_token %}
                    <div class="col-12">
                        <input type="text" class="form-control mb-3" name="username" placeholder="User Name">
                    </div>
                    <div class="col-12">
                        <input type="password" class="form-control mb-3" name="password" placeholder="Password">
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">LOGIN</button>
                    </div>
                  <p>Create an account? <a href="register" class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"  data-target="#signupModal">Register</a></p>
                </form>
            </div>
        </div>
    </div>
</div>
    {% for msg in messages %}
    <center><h3>{{msg}}</h3></center>
    {% endfor %}







<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<!-- venobox popup -->
<script src="{% static 'plugins/venobox/venobox.min.js' %}"></script>
<!-- mixitup filter -->
<script src="{% static 'plugins/mixitup/mixitup.min.js' %}"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>
<script src="{% static 'plugins/google-map/gmap.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

schoolproject/templates/order_confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>Educenter</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">
  <!-- animation css -->
  <link rel="stylesheet" href="{% static 'plugins/animate/animate.css' %}">
  <!-- aos -->
  <link rel="stylesheet" href="{% static 'plugins/aos/aos.css' %}">
  <!-- venobox popup -->
  <link rel="stylesheet" href="{% static 'plugins/venobox/venobox.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

</head>

<body>

<form class="signup-form" method="post" class="row">
                    {% csrf_token %}
<div class="card" style="width: 18rem;margin:0 auto;float:none;top:50%;">
  <img src="{% static 'images/cat-1.jpg' %}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">ORDER CONFIRMED</h5>
    <p class="card-text">Go Back To Home</p>
    <a href="{% url 'home' %}" class="btn btn-primary">Click Here</a>
  </div>
</div>

</form>



<!-- jQuery -->
<!--<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>-->
<!--&lt;!&ndash; Bootstrap JS &ndash;&gt;-->
<!--<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>-->
<!--&lt;!&ndash; slick slider &ndash;&gt;-->
<!--<script src="{% static 'plugins/slick/slick.min.js' %}"></script>-->
<!--&lt;!&ndash; aos &ndash;&gt;-->
<!--<script src="{% static 'plugins/aos/aos.js' %}"></script>-->
<!--&lt;!&ndash; venobox popup &ndash;&gt;-->
<!--<script src="{% static 'plugins/venobox/venobox.min.js' %}"></script>-->
<!--&lt;!&ndash; mixitup filter &ndash;&gt;-->
<!--<script src="{% static 'plugins/mixitup/mixitup.min.js' %}"></script>-->
<!--&lt;!&ndash; google map &ndash;&gt;-->
<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"></script>-->
<!--<script src="{% static 'plugins/google-map/gmap.js' %}"></script>-->

<!--&lt;!&ndash; Main Script &ndash;&gt;-->
<!--<script src="{% static 'js/script.js' %}"></script>-->

</body>
</html>